#!/usr/bin/env perl
use Dzpl
    name => 'Google-Search',
    version => '0.026',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Any::Moose
        Carp::Clan::Share
        JSON 2
        LWP::UserAgent
        Try::Tiny
        URI

        [Test]
        Test::Most
    /;
;

{ plugin '@ROKR' }
